INSERT INTO internship.Students (ID,Student,StudentId) VALUES
	 (1,'Ражабов Дамир Шарофович',1),
	 (2,'Сивожелезов Сергей Владимирович',2),
	 (3,'Чеснюк Дмитрий Александрович',3),
	 (4,'Мацкевич Андрей Анатольевич',4),
	 (5,'Шеронов Иван Петрович',5),
	 (6,'Гавриш Олег Николаевич',6),
	 (7,'Демьянков Владислав Витальевич',7),
	 (8,'Пехоцкий Юрий Васильевич',8),
	 (9,'Шерстюк Вадим Александрович',9),
	 (10,'Казимиров Сергей Анатольевич',10),
	 (11,'Назаров Павел Андреевич',11),
	 (12,'Шатров Игорь Олегович',12),
	 (13,'Никольский Валерий Александрович',13),
	 (14,'Гурин Сергей Владимирович',14),
	 (16,'Кузин Дмитрий Алексеевич',16),
	 (17,'Наливайко Алексей Викторович',17),
	 (18,'Чех Александр Борисович',18),
	 (19,'Есьман Михаил Михайлович',19);

INSERT INTO internship.`Result` (ID,StudentId,Task1,Task2,Task3,Task4) VALUES
	 (1,1,'pass','pass','pass','pass'),
	 (2,2,'pass','pass','pass',NULL),
	 (3,3,'pass','pass','pass','pass'),
	 (4,4,'pass','pass','not passed',NULL),
	 (5,5,'pass','pass','not passed',NULL),
	 (6,6,'pass','pass','not passed',NULL),
	 (7,7,'pass','pass','not passed',NULL),
	 (8,8,'pass','pass','pass','pass'),
	 (9,9,'pass','not passed','not passed',NULL),
	 (10,10,'pass','pass','pass','pass'),
	 (11,11,'pass','pass','pass','pass'),
	 (12,12,'pass','pass','pass','pass'),
	 (13,13,'pass','not passed','not passed',NULL),
	 (14,14,'pass','pass','pass','pass'),
	 (16,16,'pass','not passed','not passed',NULL),
	 (17,17,'pass','pass','pass',NULL),
	 (18,18,'pass','pass','pass','pass'),
	 (19,19,'pass','pass','pass','pass');
