# Ansible playbook AWS - install docker
---
- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_only: yes

- name: Ensure a list of yum packages are installed
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - python-pip
    # - mysql-devel # for MySQL-python
    - yum-utils
    - device-mapper-persistent-data
    - amazon-linux-extras

- name: Install docker-ce (centos) via amazon-linux-extras packages
  command: amazon-linux-extras install docker -y
  args:
    creates: /usr/bin/docker

- name: Enable Docker CE service at startup
  service:
    name: docker
    state: started
    enabled: yes

- name: Add the user 'ec2-user' to 'docker'
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Install docker-compose
  get_url:
    url: 'https://github.com/docker/compose/releases/download/1.28.2/docker-compose-Linux-x86_64'
    dest: /usr/local/bin/docker-compose
    mode: u=rwx,g=rx,o=rx

- name: Import a Elastic gpg key from a url
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Add Elasticrepository
  yum_repository:
    name: elastic
    description: Elastic repository for 7.x packages
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: install beats packages
  yum:
    name: ['filebeat', 'metricbeat']
    state: present
    update_cache: yes

- name: Configure filebeat
  template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0644
  notify:
  - restart filebeat

- name: Configure metricbeat
  template:
    src: metricbeat.yml
    dest: /etc/metricbeat/metricbeat.yml
    owner: root
    group: root
    mode: 0644
  notify:
  - restart metricbeat

- name: Add Metricbeat module to docker engine
  command: metricbeat modules enable docker
  args:
    creates: /etc/metricbeat/modules.d/docker.yml
  notify:
  - restart metricbeat

- name: Start Metricbeat service
  ansible.builtin.service:
    name: metricbeat
    state: started
    enabled: yes
