# Ansible playbook AWS - install docker
---
# - name: Update all packages
#   yum:
#     name: '*'
#     state: latest
#     update_only: yes

- name: Add an Apt signing key, uses whichever key is at the URL
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add specified repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Ensure a list of packages are installed
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - python-pip
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: Install docker-ce
  apt:
    name: docker-ce
    state: present

- name: Enable Docker CE service at startup
  service:
    name: docker
    state: started
    enabled: yes


- name: Add the user 'ubuntu' to 'docker'
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Install docker-compose
  get_url:
    url: 'https://github.com/docker/compose/releases/download/1.28.2/docker-compose-Linux-x86_64'
    dest: /usr/local/bin/docker-compose
    mode: u=rwx,g=rx,o=rx

- name: Gather packages facts
  package_facts:
    manager: "auto"

# todo: chanfe to install from repo like inrhel playbook
- name: Install Metricbeat package
  block:
  - name: Download Metricbeat package
    get_url:
      url: 'https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.11.1-amd64.deb'
      dest: /tmp/metricbeat-7.11.1-amd64.deb

  - name: Install Metricbeat package
    apt:
      deb: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.11.1-amd64.deb
  when: "'metricbeat' not in ansible_facts.packages"

- name: Configure beats
  template:
    src: "{{ item }}.yml"
    dest: "/etc/{{ item }}/{{ item }}.yml"
    owner: root
    group: root
    mode: 0644
  with_items:
    # - filebeat
    - metricbeat
  notify:
  - restart metricbeat

- name: Add Metricbeat module to docker engine
  command: metricbeat modules enable docker
  args:
    creates: /etc/metricbeat/modules.d/docker.yml
  notify:
  - restart metricbeat

- name: Start Metricbeat service
  ansible.builtin.service:
    name: metricbeat
    state: started
    enabled: yes

