# roles/common/tasks/main.yml
- name: Install the correct docker engine for Ubuntu
  import_tasks: Debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Install the correct docker engine for Amazon linux
  import_tasks: Amazon.yml
  when: ansible_facts['os_family']|lower == 'redhat'

# - name: Add swap file
#   import_tasks: swap.yml
#   when: swap_configure