# Ansible playbook - setup zabbix in container
---

- name: Create zabbix working directory
  file:
    path: /opt/task6
    state: directory
    owner: root
    group: root
    mode: 0755

- name: create config files
  template:
    src: "{{ item }}"
    dest: "/opt/task6/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - docker-compose.yml

- name: run docker-compose file
  command: /usr/local/bin/docker-compose up -d
  args:
    chdir: /opt/task6/

