version: "3.9"
services:
  jenkins-docker:
    image: docker:20.10-dind-rootless
    privileged: true # <-- security problems
    environment:
      DOCKER_TLS_CERTDIR: '/certs'
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    ports:
      - '2376:2376'
    restart: 'always'
    networks:
      jenkins:
        aliases:
          - docker

  jenkins:
    build: .
    depends_on:
      - jenkins-docker
    environment:
      DOCKER_HOST: 'tcp://docker:2376'
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: 1
    ports:
      - '8080:8080'
      - '50000:50000'
    restart: 'always'
    networks:
      - jenkins
    volumes:
      - type: volume
        source: jenkins-docker-certs
        target: /certs/client
        read_only: true
      - type: volume
        source: jenkins-data
        target: /var/jenkins_home
        read_only: true
      - type: bind
        source: /var/run/docker.sock # <-- security problems
        target: /var/run/docker.sock

  agent0:
    image: jenkins/ssh-agent:3.0.0-alpine
    environment:
      JENKINS_AGENT_SSH_PUBKEY: ${PUBKEY}
    ports:
      - '2222:22'
    restart: 'always'
    networks:
      - jenkins
    env_file:
      - .env

volumes:
  jenkins-docker-certs:
    # external:
    #   name: jenkins-docker-certs
  jenkins-data:
    # external:
    #   name: jenkins-data

networks:
  jenkins:
    driver: bridge
    name: jenkins
