version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000-8004:80"
    restart: 'always'
    deploy:
      replicas: 5
  java:
    image: 'docker.io/bitnami/jenkins:2-debian-10'
    depends_on:
      - mariadb
    ports:
      - '8081:8081'
      - '8443:8443'
      - '50000:50000'
    networks:
      - backend
    restart: 'always'
    volumes:
      - type: bind
        source: ./data/jenkins_data
        target: /bitnami/jenkins

  mariadb:
    image: mariadb:${MARIADB_VERSION}
    restart: 'always'
    volumes:
      - type: bind
        source: ./data/mariadb
        target: /var/lib/mysql
    networks:
      - backend
    restart: 'always'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: fake
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
networks:
  backend:
    driver: bridge