---
version: "3.9"
services:
  grafana:
    image: grafana/grafana:7.2.1
    ports:
      - 3000:3000
    volumes:
     - type: volume
       source: grafana-storage
       target: /var/lib/grafana

volumes:
  grafana-storage: